### PR TITLE
Features: Service tags and IAM role assumption

### PR DESCRIPTION
**Pull request by haeringer**
We have successfully deployed prometheus-ecs-sd at our company without issues - thank you for providing it.
With the Implementation of the below two new features, we have addressed some scalability challenges we had when using the service across multiple teams and AWS accounts.

- An additional environment variable for tagging the ECS services, similar to e.g. `__meta_consul_tags` when using Prometheus `consul_sd_config`. We use this for assigning and routing alerts to the respective teams / service code owners.

- Ability to discover services in other accounts than the one where prometheus-ecs-sd itself is running by assuming different IAM roles. An explanation of the necessary steps is provided in the readme. If assuming a role fails, the service doesn't stop but only logs the error and continues with the next role.

Suggestions or improvements are welcome :)

### CODE REVIEW

**Comment by fredsig** [comment]
Hi there, thank you for using this tool, happy to know it has been useful for you. Looking at your PR, it looks good so far. I'm setting up our first version of testing (with a test ECS cluster integration) and will be fixing a recent bug around task ids, will be back at this PR soon.

**Comment by briancurt** [comment]
@fredsig Any update on this? 🙏

**Comment by fredsig** [comment]
Apologies but I no longer maintain this repo. I do see no issues in approving this PR. @sam-burrell @aminehmida can you guys have a look? Thanks

**Comment by haeringer** [comment]
I should have put this in two separate PRs (one for the tagging feature and one for the role assumption feature), sorry for that.

At least I can tell that this version runs in production without issues for us for some months now.

**Comment by haeringer** [comment]
I'm closing this PR for now. If we'd like to have this merged again, I will open new PRs from separate, clean branches.

**Pull request closed without merging**
